apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: integration-hub-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "integration-hub"
      images:
        - alias: hub
          imageName: islem12/integration-hub
          commonUpdateSettings:
            updateStrategy: latest
          manifestTargets:
            helm:
              name: hub.repository
              tag: hub.tag
