apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: integration-hub-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "integration-hub"
      useAnnotations: true
