apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mock-cfec-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-cfec
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-cfec
  template:
    metadata:
      labels:
        app: mock-cfec
    spec:
      containers:
        - name: mock-cfec
          image: mock-cfec-service-mock-cfec:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: mock-storage
              mountPath: /app/storage
      volumes:
        - name: mock-storage
          persistentVolumeClaim:
            claimName: mock-cfec-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mock-cfec
spec:
  selector:
    app: mock-cfec
  ports:
    - port: 4000
      targetPort: 4000
