apiVersion: v1
kind: Secret
metadata:
  name: hub-secrets
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  HUB_CRYPTO_SECRET_KEY: {{ .Values.secrets.cryptoSecretKey | quote }}
  N8N_WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
  HUB_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
